### ISSUE TITLE
might want to also include the hash of the WIT in the proof

### ISSUE THREAD

**Issue by bc-pi** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#24]
>  You might want to also include the hash of the WIT in the proof of possession.  Perhaps just having the full name is good enough, but I think you want to account for the issuer of the WIT as well in the signature.

_Originally posted by @jsalowey in https://github.com/yaronf/wimse-s2s/pull/19#discussion_r1646749641_

**Comment by jsalowey** [comment]
If the WIT is not included in the signature I think you can end up in a situation where the client and server have a different understanding of what was authenticated on the connection.  The workload identity is arguably the most important piece of information which is already included in the signature, but the WIT contains other information as well. For example the issuer that signed that token although this should be mapped to the workload ideneity there could be differences in some cases.  In addition if the WIT contains any other fields that contain important information then the client and server can have processed.  
I'm pretty convinced that we should include the WIT in the signature.  Perhaps we can get away with it if the WIT really only contains the workload identity and not other information (no extensions) and we are confident that deployments will get the trust root configuration for token validation correct.

**Comment by yaronf** [comment]
Maybe we should clarify that a WIT must only contain identity information, and not authorization/policy. But we all know that people ignore such warnings.

**Comment by PieterKas** [comment]
@joe-venafi is there an attack you can describe that may result from not signing the WIT (even if it does not include other claims). For example, is it possible to swap out a proof from one domain to another if the issuer information is not taken into account (would require the key material to be duplicated)? If there is, we should note it in the security considerations as motivation for including the WIT hash.

**Comment by arndt-s** [comment]
@PieterKas I can give this a try:

Situation:
```mermaid
flowchart LR
WorkloadA --> ReverseProxy --> WorkloadB
```

1. WorkloadA -> ReverseProxy
   ```
   Workload-Identity-Token: T1
   Workload-Proof-Token: P1
   ```

2. ReverseProxy -> WorkloadB
ReverseProxy swaps T1 (or P1) to T2 (or P2).
   ```
   Workload-Identity-Token: T2
   Workload-Proof-Token: P1
   ```

The attack is not as simple as this, T2 claims still need to match P1, but looking at the theory:
**there is no guarantee that the P1 was actually generated for T1 and not T2. As long as claims of the WIT match the proof it is accepted.**

**Comment by jsalowey** [comment]
Thanks @arndt-s this the mechanism, if any substantive is different between the two tokens (probably anything other than the ID and the expiration time) then the receiver will have a different world view of the state after authentication than the sender.  Even a unique identtifier such as a JTI could be problematic if the system uses it to associate the token with other data.  
@PieterKas I will add some security considerations on this.

**Comment by arndt-s** [comment]
We added this in https://github.com/ietf-wg-wimse/draft-ietf-wimse-s2s-protocol/pull/66. 

A follow up issue regarding the `iss` claim in the WPT has been created: https://github.com/ietf-wg-wimse/draft-ietf-wimse-s2s-protocol/issues/68
