### ISSUE TITLE
a construct that's both simple and extensible(?)

### ISSUE THREAD

**Issue by bc-pi** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#25]
> Although we can definitely punt on it for now, I think we could choose a construct that's both simple and extensible.
>
>```json
>"signed_headers": {
>    "txn-token": "txn token hash",
>    "x-custom-context": "x-custom-context hash"
>}
>```
> Unfortunately we need the WPT to sign miscellaneous stuff, because we don't want a new WIT for every call. Having said that, as far as I can tell it does NOT need to sign the WIT itself.

_Originally posted by @yaronf in https://github.com/yaronf/wimse-s2s/pull/19#discussion_r1648132681_

**Comment by bc-pi** [comment]
https://github.com/yaronf/wimse-s2s/pull/19#discussion_r1655448211 related followup in the aforementioned comment

**Comment by yaronf** [comment]
Won't do, too complex.
