### ISSUE TITLE
Clarification of "For those who celebrate" phrase

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#37]
Commenting as identity enthusiast as opposed to WIMSE co-chair:

Section 4.1.1, paragraph 2 starts with "For those who celebrate..." Is this an auto-correct error, or does it have some specific meaning in the context of ABNF notation?

**Comment by bc-pi** [comment]
It's a subtle attempt at a little bit of humor. ChatGPT explains the general phrase thusly: 

> The phrase "for those who celebrate" is often used to acknowledge that not everyone may participate in a particular holiday, event, or tradition. It's a way of being inclusive and respectful of diverse beliefs, practices, and customs. For example, saying "Happy Holidays to those who celebrate" recognizes that while some people may be celebrating a specific holiday, others may not observe it or may celebrate different holidays.

The meaning in the context of this document is to playfully acknowledge that some people really like ABNF while others aren't readily familiar with it and don't find it particularly useful. 

Of course, if the joke has to be explained...

**Comment by yaronf** [comment]
See also #32.
