### ISSUE TITLE
Extensibility of the Workload Proof Token

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#38]
Commenting as identity enthusiast as opposed to WIMSE co-chair:

It may be helpful to make the proof mechanism extensible and allow for the inclusion of additional elements that may be included in the proof (similar to DPoP).

**Comment by bc-pi** [comment]
There is nothing currently precluding additional stuff in the proof. I know DPoP says something about it being okay for the proof to contain other information (end of this paragraph https://www.rfc-editor.org/rfc/rfc9449.html#section-4.2-12) but it's not necessary to allow it.

**Comment by arndt-s** [comment]
I believe there's a broader discussion on "What proof of possession attributes do we want" if we go down the DPoP-ish route. HTTP message signatures come with the capability to let the implementer choose what property the signature covers. (whether this is good or not).

I personally don't know yet and I'm hoping IETF120 will give new perspectives.

**Comment by yaronf** [comment]
After considering the differences between HTTP Message Sigs and the DPoP mechanisms we decided to limit extensibility of this one.
