### ISSUE TITLE
Inconsistency between DPoP and HTTP Signature

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#41]
Commenting as identity enthusiast as opposed to WIMSE co-chair:

The HTTP Signature proposal requires the Workload Identity Token to be signed, but the Workload Proof Token does not include a mechanism for signing the Workload Identity Token. Proposal is to include signing of the Workload Identity Token in both to avoid asymmetric security values.

**Comment by bc-pi** [comment]
I dare say the document authors do not (at this point anyway) agree on the need for the WIT to be covered by the proof signature https://github.com/yaronf/wimse-s2s/issues/24 

Meanwhile the eventual goal is to choose just one of the DPoP-inspired and HTTP Signature based approaches. So I don't know that there's much value in trying to make them the same for the sake of avoiding asymmetric security values.

**Comment by yaronf** [comment]
Fixed:
- Signing the WIT in WPT
- Consistency between Message Sig and PoP is no longer a goal.

**Comment by arndt-s** [comment]
for reference, added in https://github.com/ietf-wg-wimse/draft-ietf-wimse-s2s-protocol/pull/66
