### ISSUE TITLE
PKIX Path Validation

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#44]
Commenting as identity enthusiast as opposed to WIMSE co-chair

In section 5, which PKIX path validation rules apply (all of them?).

**Comment by yaronf** [comment]
Probably all, RFC 5280.

**Comment by jsalowey** [comment]
+1

**Comment by yaronf** [comment]
Is this resolved by #63 ?

**Comment by jsalowey** [comment]
Yes I think so/

**Comment by yaronf** [comment]
Fixed
