### ISSUE TITLE
X.509 fields

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#46]
Commenting as identity enthusiast as opposed to WIMSE co-chair

Section 5 states that the identifier may be used in an X.509 certificate. From reading the draft, this may be a client or a server certificate. Should we included additional details about the certificates themeselves? Should a workload be able to use the same certificate for client authentication and as a server? What are the extended key usage parameters that should be supported (can a cert have both)?

**Comment by jsalowey** [comment]
PR#63 adds some of this.  We may want to make more specification around what can be in the URI (no port, username; trust domain lowercase)

**Comment by jsalowey** [comment]
This issue is addressed by text in section 5 an section 3.
