### ISSUE TITLE
How to validate if a CA is authorized to issue WIMSE credentials

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#47]
Commenting as identity enthusiast as opposed to WIMSE co-chair:

Is there an existing mechanism that a verifier can use to determine that the CA is authorized to issue WIMSE credentials (certificates)?

**Comment by yaronf** [comment]
Talk about a trust store? Mapping of trust domains to CAs? Discovery mechanism for that?

**Comment by yaronf** [comment]
Need to clarify: a specific trust store. No "key usage".

**Comment by jsalowey** [comment]
The existing mechanisms for certificate path validation validate that the certificate is signed by certificate that chains up to a trusted root.  Validating that this issuer is authorized to issue Wimse credentials would require additional steps.  

One possible additional step is to maintain a configuration that maps a trust domain present in a WIMSE identifier to a particular trust root.  This could be done by either using the trust domain portion of the WIMSE identifier to select the CA trust root that is used for path validation or to go through path validation with an existing trust to and verify the trust domain maps to the root certificate used to validate the credential after the fact.   We could also define a discovery mechanism to discover this configuration, perhaps through a well know URI path or through DNS (both would have some difficult security considerations.  

If you already have trust established with a particular trust anchor for authorizing WIMSE then you could possibly use certificate fields to authorize the issuer.  Theoretically, naming constraints to could used to constrain a particular sub-CA to only issue credentials for a particular trust domain.  One could also define other extensions or extended key usages that could relate to WIMSE, but that would need to be defined.  

I think it would be best to start with a requirement for a configuration of trust domain to a CA.

**Comment by yaronf** [comment]
@jsalowey Can you open a PR for this? Personally I would go for the simplest configuration, where provisioning of this configuration is out of scope.

**Comment by jsalowey** [comment]
#62

**Comment by yaronf** [comment]
Fixed.
